version: "3.8"
services:
  objectbox:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-objectbox
      - APPLICATION_NAME=db-objectbox
    expose:
      - "8080"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
  mapdb:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-mapdb
      - APPLICATION_NAME=db-mapdb
    expose:
      - "8080"
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
  nitrite:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-nitrite
      - APPLICATION_NAME=db-nitrite
    expose:
      - "8080"
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
  taurus:
    image: blazemeter/taurus
    volumes:
      - ./taurus/:/bzt-configs
    command:
      "taurustest.yml -report"
  springbootserver:
    image: slydeveloper/spring-boot-admin:latest
    environment:
      - SPRING_BOOT_ADMIN_SECURITY_ENABLED=false
    expose:
      - "1111"
    ports:
      - "1111:1111"
