version: "3.8"
services:
  objectbox:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-objectbox
    expose:
      - "8080"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  mapdb:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-mapdb
    expose:
      - "8080"
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  taurus:
    build: taurus/.
    volumes:
      - ./taurus/:/bzt-configs
    command:
      "taurustest.yml -report"
    environment:
      - WAIT_HOSTS=objectbox:8080, mapdb:8080
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
