version: "3.8"
services:
  objectbox:
    build:
      context: .
      args:
        - JAVA_OPTIONS=-Xmx400m -Xms100m
    environment:
      - SPRING_PROFILES_ACTIVE=db-objectbox
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://springbootserver:1111
    expose:
      - "8080"
    ports:
      - "10001:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
  mapdb:
    build:
      context: .
      args:
        - JAVA_OPTIONS=-Xmx400m -Xms100m
    environment:
      - SPRING_PROFILES_ACTIVE=db-mapdb
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://springbootserver:1111
    expose:
      - "8080"
    ports:
      - "10002:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
  nitrite:
    build:
      context: .
      args:
        - JAVA_OPTIONS=-Xmx400m -Xms100m
    environment:
      - SPRING_PROFILES_ACTIVE=db-nitrite
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://springbootserver:1111
    expose:
      - "8080"
    ports:
      - "10003:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
  mongo:
    build:
      context: .
      args:
        - JAVA_OPTIONS=-Xmx400m -Xms100m
    environment:
      - SPRING_PROFILES_ACTIVE=db-mongo
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://springbootserver:1111
    expose:
      - "8080"
    ports:
      - "10004:8080"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
  taurus:
    build: taurus/.
    volumes:
      - ./taurus/:/bzt-configs
    command:
      "taurustest.yml -report"
    environment:
      - WAIT_HOSTS=objectbox:8080, mapdb:8080, nitrite:8080, mongo:8080, prometheus:9090, grafana:3000, springbootserver:1111
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
  springbootserver:
    image: slydeveloper/spring-boot-admin:latest
    environment:
      - SPRING_BOOT_ADMIN_SECURITY_ENABLED=false
    expose:
      - "1111"
    ports:
      - "1111:1111"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards
    ports:
      - 3000:3000
