version: "3.8"
services:
  objectbox:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-objectbox
    expose:
      - "8080"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
  mapdb:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-mapdb
    expose:
      - "8080"
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 200M
  taurus:
    image: blazemeter/taurus
    volumes:
      - ./taurus/:/bzt-configs
    command:
      "taurustest.yml -report"
