version: "3.8"
services:
  objectbox:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-objectbox
      - APPLICATION_NAME=db-objectbox
    expose:
      - "8080"
    ports:
      - "10001:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  mapdb:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-mapdb
      - APPLICATION_NAME=db-mapdb
    expose:
      - "8080"
    ports:
      - "10002:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  nitrite:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=db-nitrite
      - APPLICATION_NAME=db-nitrite
    expose:
      - "8080"
    ports:
      - "10003:8080"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
  taurus:
    build: taurus/.
    volumes:
      - ./taurus/:/bzt-configs
    command:
      "taurustest.yml -report"
    environment:
      - WAIT_HOSTS=objectbox:8080, mapdb:8080, nitrite:8080, prometheus:9090, springbootserver:1111
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
  springbootserver:
    image: slydeveloper/spring-boot-admin:latest
    environment:
      - SPRING_BOOT_ADMIN_SECURITY_ENABLED=false
    expose:
      - "1111"
    ports:
      - "1111:1111"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
